# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - run: npm ci
    - run: ng build --configuration "production" --base-href="https://root-collective.github.io/box-management-app/"
    - name: Run headless test
      run: ng test --watch=false --browsers=ChromeHeadless --code-coverage
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist/box-management-app/browser'

  deploy:
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write


    runs-on: ubuntu-latest

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
